### ISSUE TITLE
Can't load CLI

### ISSUE THREAD

**Issue by 0xnexusflip** [0xweb-org/0xweb#1]
After installing the package through npm and trying to run it the following error shows up:

`Unknown command: /opt/homebrew/Cellar/node/19.2.0/bin/node
    at CommandsHandler.findCommand (/opt/homebrew/lib/node_modules/0xweb/lib/cli.js:3234:19)
    at App.execute (/opt/homebrew/lib/node_modules/0xweb/lib/cli.js:24305:79)
    at async App.runFromCli (/opt/homebrew/lib/node_modules/0xweb/lib/cli.js:24326:13)`
    
Tested on Ubuntu, MacOS and Windows

**Comment by tenbits** [comment]
Thank you for reporting this. We couldn't reproduce this with nodejs 18/19 for known commands. How do you run the command, and which? Simply the `0xweb`? In that case, the `--help` command is executed, identical to `0xweb --help`.  Can you try to print out the version: `0xweb -v`

It looks like the command is an empty string. `0xweb` has no commands, that's why the default (`--help`) is taken, but I could reproduce it with `0xweb ""`.

**Comment by 0xnexusflip** [comment]
I tried running both `0xweb init`and `0xweb --help`. Also tried `0xweb -v` and the same issue occurs. Find it odd for it to happen on all my different workspaces regardless of the OS used...

So in your case it works normally? I even tried to manually uninstall all deprecated/outdated dependencies and replace them with the most recent/updated ones and also did not work. Would appreciate further guidance as I need to automate some Gnosis Safe tx proposals ASAP and using this lib seems like the most appropriate and simple option, provided I can get it to work.

**Comment by 0xnexusflip** [comment]
Also for reference I'm using node v19.2.0.

**Comment by tenbits** [comment]
There is a fresh version published `0.9.57`. The issue should be fixed now. In case something new dives use this or a new issue. 
Thank you.

**Comment by 0xnexusflip** [comment]
It works now. Thank you so much for your assistance, I really appreciate it!
